apiVersion: v1
baseDomain: $OCP_BASE_DOMAIN
controlPlane:
  architecture: amd64
  hyperthreading: Enabled
  name: master
  platform:
    aws:
      rootVolume:
        iops: 4000
        size: 500
        type: io1
      type: m5.xlarge
      zones:
      - us-east-1b
      - us-east-1c
      - us-east-1d
  replicas: 3
compute:
- architecture: amd64
  hyperthreading: Enabled
  name: worker
  platform:
    aws:
      rootVolume:
        iops: 2000
        size: 500
        type: io1
      type: m5.large
      zones:
      - us-east-1b
      - us-east-1c
      - us-east-1d
  replicas: 3
metadata:
  creationTimestamp: null
  name: $OCP_CLUSTER_NAME
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/19
    hostPrefix: 23
  machineNetwork:
  - cidr: 10.0.0.0/24
  networkType: OpenShiftSDN
  serviceNetwork:
  - 172.30.0.0/19
platform:
  aws:
    region:          $REGION
    userTags:
      adminContact:  cloudxabide@gmail.com
      costCenter:    8675309
      purpose:       'IPI Installation Testing'
      notes:         'Testing extensible tagging'
      environment:   'Test'
fips: false
publish: External
pullSecret: '$PULL_SECRET'
sshKey: '$SSH_KEY'
