apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  labels:
    machine.openshift.io/cluster-api-cluster: '$INFRASTRUCTURE_ID' 
  name: '$INFRASTRUCTURE_ID'-'$ROLE'-'$ZONE' 
  namespace: openshift-machine-api
spec:
  replicas: 1
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: '$INFRASTRUCTURE_ID' 
      machine.openshift.io/cluster-api-machineset: '$INFRASTRUCTURE_ID'-'$ROLE'-'$ZONE' 
  template:
    metadata:
      labels:
        machine.openshift.io/cluster-api-cluster: '$INFRASTRUCTURE_ID' 
        machine.openshift.io/cluster-api-machine-role: '$ROLE' 
        machine.openshift.io/cluster-api-machine-type: '$ROLE' 
        machine.openshift.io/cluster-api-machineset: '$INFRASTRUCTURE_ID'-'$ROLE'-'$ZONE' 
    spec:
      metadata:
        labels:
          node-role.kubernetes.io/'$ROLE': "" 
      providerSpec:
        value:
          ami:
            id: ami-046fe691f52a953f9 
          apiVersion: awsproviderconfig.openshift.io/v1beta1
          blockDevices:
            - ebs:
                iops: 0
                volumeSize: 120
                volumeType: gp2
          credentialsSecret:
            name: aws-cloud-credentials
          deviceIndex: 0
          iamInstanceProfile:
            id: '$INFRASTRUCTURE_ID'-worker-profile 
          instanceType: m4.large
          kind: AWSMachineProviderConfig
          placement:
            availabilityZone: '$ZONE'
            region: '$REGION'
          securityGroups:
            - filters:
                - name: tag:Name
                  values:
                    - '$INFRASTRUCTURE_ID'-worker-sg 
          subnet:
            filters:
              - name: tag:Name
                values:
                  - '$INFRASTRUCTURE_ID'-private-'$ZONE' 
          tags:
            - name: kubernetes.io/cluster/'$INFRASTRUCTURE_ID' 
              value: owned
          userDataSecret:
            name: worker-user-data
